management:
    endpoints:
        web:
            exposure:
                include: '*'
oracle:
    datasource:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        driverClassName: oracle.jdbc.OracleDriver
        password: Haslo123
        url: jdbc:oracle:thin:@localhost:1521:XE
        username: USOS_PROD_TAB
pl.poznan.ue.matriculation:
    admin:
        userName: casuser
    cas:
        url: https://casserver.herokuapp.com/cas
    defaultStudentOrganizationalUnit: UEP
    dreamApplyApiKey: rcbogew2JePfxpx4seYWssCzTsVu4qCL
    dreamApplyInstance: https://apply.ue.poznan.pl
    incomingApiKey: YFS9hdk4BodcwLAqujNp8s6AJLnFppbS
    incomingInstance: https://incoming.ue.poznan.pl
    ldap:
        base: DC=ue,DC=poznan
        dn: CN=72846,OU=Pracownik,OU=all,DC=ue,DC=poznan
        password: FigosFagos05
        url: ldap://ad01.ue.poznan:389/?(objectClass=*)
    primaryIrkInstance: https://e-rekrutacja.ue.poznan.pl
    primaryIrkInstanceKey: 598050a3c1978e84cb7dc0f43d4e2a091ff76319
    primaryIrkInstanceSetAsAccepted: false
    service:
        home: https://spring.mkubiak.it
    testIrkInstance: https://usos-irk.ue.poznan.pl
    testIrkInstanceKey: 598050a3c1978e84cb7dc0f43d4e2a091ff76319
    testIrkInstanceSetAsAccepted: false
    universityEmailSuffix: ue.poznan.pl
    usos:
        url: http://localhost:8080/usosadm
server:
    port: 8081
#    ssl:
#        key-store-type: jks
#        key-store: /home/michal/michal-pc.jks
#        key-store-password: FigosFagos05
#        key-alias: michal-pc
#        enabled: true
spring:
    datasource:
        database-platform: org.hibernate.dialect.H2Dialect
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        database: default
        properties:
            hibernate:
                format_sql: true
                generate_statistics: false
    main:
        allow-bean-definition-overriding: true
    devtools:
        restart:
            trigger-file: "/home/michal/restart.txt"
log4jdbc:
    drivers: org.h2.Driver,oracle.jdbc.OracleDriver
    debug.stack.prefix: ^pl\.poznan\.ue\.matriculation.*
    sqltiming:
        warn.threshold: 1
        error.threshold: 1

