app:
    service:
        security: ${pl.poznan.ue.matriculation.service.home}/login/cas
cas:
    service:
        login: ${pl.poznan.ue.matriculation.cas.url}/login
        logout: ${pl.poznan.ue.matriculation.cas.url}/logout
    ticket:
        validate:
            url: ${pl.poznan.ue.matriculation.cas.url}/
management:
    endpoints:
        web:
            exposure:
                include: httptrace
    endpoint:
        health:
            show-details: when_authorized
            roles: 'ROLE_ADMIN'
            probes:
                enabled: true
server:
    error:
        include-message: always
spring:
    jpa:
        open-in-view: false
        generate-ddl: false
        #        repositories:
        #            bootstrap-mode: lazy
        properties:
            hibernate:
                jdbc:
                    time_zone: CET
                    batch_size: 100
                    fetch_size: 400
                order_inserts: true
                order_updates: true
                query:
                    in_clause_parameter_padding: true
    profiles:
        active: '@spring.profiles.active@'

pl.poznan.ue.matriculation:
    clause.and.regulation2:
        regulations:
            -   code: SLU_STUD
                programmePattern: ^S[1..2]-.*$
            -   code: SLU_STUD_NS
                programmePattern: ^N[1..2]-.*$

