-- insert into Role
-- values ('IMPORT_PROGRESS', 'Oglądanie progresu');
-- insert into Role
-- values ('IMPORT_SAVE', 'Uruchamianie zapisywania w usosie');
-- insert into Role
-- values ('IMPORT_DATA_SOURCES', 'Wyświetlanie listy źródeł danych');
-- insert into Role
-- values ('IMPORT_ARCHIVE', 'Archiwizacja importów');
-- insert into Role
-- values ('IMPORT_CHANGE_INDEX', 'Zmiana indeksów');
-- insert into Role
-- values ('USOS_DICTIONARIES', 'Dostęp do słowników usos');
-- insert into Role
-- values ('IMPORT_VIEW_APPLICATIONS', 'Oglądanie zgłoszeń');
-- insert into Role
-- values ('IMPORT_IMPORT_APPLICATIONS', 'Uruchamianie importu zgłoszeń');
-- insert into Role
-- values ('IMPORT_VIEW', 'Oglądanie importów');
-- insert into Role
-- values ('IMPORT_CREATE', 'Tworzenie importów');
-- insert into Role
-- values ('IMPORT_DELETE', 'Usuwanie importów');
-- insert into Role
-- values ('IMPORT_LDAP', 'Przeglądanie Active directory (Uidów)');
