export type ImportStatus =
  'PENDING'
  | 'STARTED'
  | 'IMPORTED'
  | 'SAVING'
  | 'COMPLETE'
  | 'ARCHIVED'
  | 'COMPLETED_WITH_ERRORS'
  | 'ERROR'
  | 'SENDING_NOTIFICATIONS'
  | 'SEARCHING_UIDS';

